name: Release

on:
#  release:
#    types: [ published ]
  push:
    branches:
      - master # master 分支 push 时触发工作流

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ''
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
        run: pnpm tauri build # 假设 build 是你的 npm 脚本命令

  update:
    needs: release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Create Update
        run: pnpm run update # 假设 update 是你的 npm 脚本命令
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
